title = "Coding Testing"  # From Git
gitRepoUrl = "https://github.com/BoredDynasty/Code_Testing" # From Git

gitSourceBranch = "main"
changelog = true
classOrder = []

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"

[footer]
style = "dark"
copyright = "Copyright © 2021 OfficialDynasty. Built with Moonwave and Docusaurus"